server:
  port: 8081

app:
  timeout: 30000
  service:
    dictionary-service: ${CLUSTER_HOST:dictionary-service}/api/dictionary-service

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${app.timeout}



spring:
  rabbitmq:
    host: ${CLUSTER_HOST:rabbitmq}

---

spring:
  profiles: docker

app:
  timeout: 3000
server:
  port: 8080