server:
  port: 8081

app:
  service:
    dictionary-service: http://server/api/dictionary-service

hystrix:
  shareSecurityContext: true

spring:
  rabbitmq:
    host: ${CLUSTER_HOST:rabbitmq}

---

spring:
  profiles: docker
server:
  port: 8080