eureka:
  client:
    serviceUrl:
      defaultZone: http://${CLUSTER_HOST:discovery}:8761/eureka/
  instance:
    preferIpAddress: true


spring:
  datasource:
    url: jdbc:mysql://${CLUSTER_HOST}:33060/lingvo-movie
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    hibernate:
      ddl-auto: update
  data:
   rest:
     return-body-on-create: true
     return-body-on-update: true


---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/lingvo-movie