eureka:
  client:
    serviceUrl:
      defaultZone: http://${CLUSTER_HOST:discovery}:8761/eureka/
  instance:
    preferIpAddress: true

facebook:
  client:
    clientId: 216860685383630
    clientSecret: 14e99b601930d5464e5d348f97a72a71
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    #pre-established-redirect-uri: http://localhost:3000/login
    #registered-redirect-uri: http://localhost:3000/login
    #use-current-uri: false
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://${CLUSTER_HOST}:33060/lingvo-movie
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    hibernate:
      ddl-auto: update
  data:
   rest:
     return-body-on-create: true
     return-body-on-update: true

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/lingvo-movie