server:
  context-path: /api/account-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://${CLUSTER_HOST:discovery}:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.security: DEBUG

facebook:
  client:
    clientId: 216860685383630
    tokenName: access_token
  resource:
    userInfoUri: https://graph.facebook.com/me

spring:
  datasource:
    url: jdbc:mysql://${CLUSTER_HOST}:33060/lingvo-movie
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    hibernate:
      ddl-auto: update
  data:
   rest:
     return-body-on-create: true
     return-body-on-update: true

---

spring:
  profiles: docker
server:
  context-path: /
  datasource:
    url: jdbc:mysql://mysql:3306/lingvo-movie